name: Weekly Database Backup

# on:
#   schedule:
#     - cron: "20 * * * *" # Runs at 00:00 every Sunday
on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y-%m-%d_%H-%M-%S_%Z')" >> $GITHUB_ENV

      - name: Use DATE variable
        run: |
          echo "The DATE is $DATE"
          # Use $DATE to construct filenames or for other purposes
      - name: SSH and execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export PGPASSWORD='${{ secrets.DB_PASSWORD }}'
            # DATE=$(date +'%Y-%m-%d_%H-%M-%S_%Z')
            FILENAME="${{ secrets.DB_NAME }}_$DATE.sql"
            pg_dump -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} > "~/backups/$FILENAME"
            echo "FILENAME=$FILENAME" >> $GITHUB_ENV # Pass the filename to the next step

      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: TRNR BACKUP - ${{ env.FILENAME }} Database Backup Completed
          body: |
            Backup of database ${{ secrets.DB_NAME }} was successfully created. 
            Filename: ${{ env.FILENAME }}
          to: visheshdubey2016@gmail.com
          from: 💾 Weekly Database Backup -  <info@trnr.com>
