name: Weekly Database Backup

# on:
#   schedule:
#     - cron: "20 * * * *" # Runs at 00:00 every Sunday
on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up PostgreSQL client
      #   run: sudo apt-get install -y postgresql-client
      - name: SSH and execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export PGPASSWORD='${{ secrets.DB_PASSWORD }}'
            DATE=$(date +'%Y-%m-%d')
            mkdir -p ~/backups
            pg_dump -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} > ~/backups/${{ secrets.DB_NAME }}_$DATE.sql
      # - name: Dump database
      #   env:
      #     PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      #   run: |
      #     DATE=$(date +'%Y-%m-%d')
      #     pg_dump -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} > ${{ secrets.DB_NAME }}_$DATE.sql

      # - name: Upload backup to repository (Optional)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Database Backup
      #     path: ${{ secrets.DB_NAME }}_*.sql

      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Database Backup Completed
          body: Backup of database ${{ secrets.DB_NAME }} was successfully created.
          to: visheshdubey2016@gmail.com
          from: GitHub Actions <info@trnr.com>
