name: Deploy Strapi Backend

on:
  push:
    branches:
      - main

jobs:
   checkout_code:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  # Job to execute commands on the server via SSH
  ssh_execute:
    name: SSH and execute commands on the server
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
      - name: SSH and execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          # Run commands on the server
          script: |
            cd ~/trnr-backend-test
            git pull origin main
            yarn install --frozen-lockfile
            pm2 restart ecosystem.config.js
